export const books = [
  {
    BookID: 1,
    Name: "Thám Tử Lừng Danh Conan - Tập 96",
    Author: "Gosho Aoyama",
    CategoryID: "Truyện tranh",
    PublisherID: "NXB Lao Động",
    QuantityIn: 100,
    QuantityOut: 25,
    OriginalPrice: 10000,
    Price: 16000,
    ImageLink: "",
    Dimensions: "1cm x 2cm",
    Weight: 0.48,
    NumberOfPage: 78,
    Information: "Là 1 cuốn sách thật tuyệt vời",
    Date: "10/05/2019",
    Format: "soft",
  },
  {
    BookID: 2,
    Name: "Thám Tử Lừng Danh Conan - Tập 96",
    Author: "Gosho Aoyama",
    CategoryID: "Truyện tranh",
    PublisherID: "NXB Lao Động",
    QuantityIn: 100,
    QuantityOut: 25,
    OriginalPrice: 10000,
    Price: 16000,
    ImageLink: "",
    Dimensions: "1cm x 2cm",
    Weight: 0.48,
    NumberOfPage: 78,
    Information: "Là 1 cuốn sách thật tuyệt vời",
    Date: "10/05/2019",
    Format: "soft",
  },
  {
    BookID: 3,
    Name: "Thám Tử Lừng Danh Conan - Tập 96",
    Author: "Gosho Aoyama",
    CategoryID: "Truyện tranh",
    PublisherID: "NXB Lao Động",
    QuantityIn: 100,
    QuantityOut: 25,
    OriginalPrice: 10000,
    Price: 16000,
    ImageLink: "",
    Dimensions: "1cm x 2cm",
    Weight: 0.48,
    NumberOfPage: 78,
    Information: "Là 1 cuốn sách thật tuyệt vời",
    Date: "10/05/2019",
    Format: "soft",
  },
  {
    BookID: 4,
    Name: "Thám Tử Lừng Danh Conan - Tập 96",
    Author: "Gosho Aoyama",
    CategoryID: "Truyện tranh",
    PublisherID: "NXB Lao Động",
    QuantityIn: 100,
    QuantityOut: 25,
    OriginalPrice: 10000,
    Price: 16000,
    ImageLink: "",
    Dimensions: "1cm x 2cm",
    Weight: 0.48,
    NumberOfPage: 78,
    Information: "Là 1 cuốn sách thật tuyệt vời",
    Date: "10/05/2019",
    Format: "soft",
  },
  {
    BookID: 5,
    Name: "Thám Tử Lừng Danh Conan - Tập 96",
    Author: "Gosho Aoyama",
    CategoryID: "Truyện tranh",
    PublisherID: "NXB Lao Động",
    QuantityIn: 100,
    QuantityOut: 25,
    OriginalPrice: 10000,
    Price: 16000,
    ImageLink: "",
    Dimensions: "1cm x 2cm",
    Weight: 0.48,
    NumberOfPage: 78,
    Information: "Là 1 cuốn sách thật tuyệt vời",
    Date: "10/05/2019",
    Format: "soft",
  },
];
export const users = [
  {
    id: 1,
    username: "abc",
    name: "Nguyen Van A",
    registerDate: "10/05/2019",
    role: 1,
    status: "active",
  },
  {
    id: 2,
    username: "def",
    name: "Nguyen Van A",
    registerDate: "10/05/2019",
    role: 1,
    status: "active",
  },
  {
    id: 3,
    username: "ghi",
    name: "Nguyen Van A",
    registerDate: "10/05/2019",
    role: 0,
    status: "active",
  },
  {
    id: 4,
    username: "mno",
    name: "Nguyen Van A",
    registerDate: "10/05/2019",
    role: 0,
    status: "active",
  },
];
