export const books = [
  {
    id: 1,
    name: "Thám Tử Lừng Danh Conan - Tập 96",
    author: "Gosho Aoyama",
    type: "Truyện tranh",
    publisher: "NXB Lao Động",
    inputQuantity: 100,
    sold: 25,
    originalPrice: 10000,
    price: 16000,
    dimension: "1cm x 2cm",
    weight: 0.48,
    numberOfPages: 78,
    info: "Là 1 cuốn sách thật tuyệt vời",
    inputDate: "10/05/2019",
    coverType: "soft",
  },
  {
    id: 2,
    name: "Đọc Vị Bất Kì Ai (Tái Bản)",
    author: "TS. David J. Lieberman",
    type: "Sách kinh tế",
    publisher: "NXB Lao Động",
    inputQuantity: 20,
    sold: 20,
    originalPrice: 35000,
    price: 52000,
    dimension: "1cm x 2cm",
    weight: 0.48,
    numberOfPages: 78,
    info: "Là 1 cuốn sách thật tuyệt vời",
    inputDate: "10/05/2019",
    coverType: "soft",
  },
  {
    id: 3,
    name: "Sự Cứu Rỗi Của Thánh Nữ",
    author: "Higashino Keigo",
    type: "Sách văn học",
    publisher: "NXB Lao Động",
    inputQuantity: 20,
    sold: 20,
    originalPrice: 27000,
    price: 54000,
    dimension: "1cm x 2cm",
    weight: 0.48,
    numberOfPages: 78,
    info: "Là 1 cuốn sách thật tuyệt vời",
    inputDate: "10/05/2019",
    coverType: "soft",
  },
  {
    id: 4,
    name: "Mắt Biếc",
    author: "Nguyễn Nhật Ánh",
    type: "Sách văn học",
    publisher: "NXB Trẻ",
    inputQuantity: 20,
    sold: 20,
    originalPrice: 10000,
    price: 16000,
    dimension: "1cm x 2cm",
    weight: 0.48,
    numberOfPages: 78,
    info: "Là 1 cuốn sách thật tuyệt vời",
    inputDate: "10/05/2019",
    coverType: "soft",
  },
  {
    id: 5,
    name: "Sự Im Lặng Của Bầy Cừu",
    author: "Higashino Keigo",
    type: "Sách văn học",
    publisher: "NXB Lao Động",
    inputQuantity: 20,
    sold: 20,
    originalPrice: 10000,
    price: 16000,
    dimension: "1cm x 2cm",
    weight: 0.48,
    numberOfPages: 78,
    info: "Là 1 cuốn sách thật tuyệt vời",
    inputDate: "10/05/2019",
    coverType: "soft",
  },
];
export const users = [
  {
    id: 1,
    username: "abc",
    name: "Nguyen Van A",
    registerDate: "10/05/2019",
    role: 1,
    status: "active",
  },
  {
    id: 2,
    username: "def",
    name: "Nguyen Van A",
    registerDate: "10/05/2019",
    role: 1,
    status: "active",
  },
  {
    id: 3,
    username: "ghi",
    name: "Nguyen Van A",
    registerDate: "10/05/2019",
    role: 0,
    status: "active",
  },
  {
    id: 4,
    username: "mno",
    name: "Nguyen Van A",
    registerDate: "10/05/2019",
    role: 0,
    status: "active",
  },
];
